theme: alembic-jekyll-theme
title: My website
logo: 'https://www.gravatar.com/avatar/6c0377abcf4da91cdd35dea4554b2a4c?s=52'
baseurl: ''
permalink: pretty
collections:
  posts:
    title: Posts
    output: true
    description: My thoughts and ideas
    feature_text: |
      Welcome to my blog
    feature_image: 'https://picsum.photos/2560/600?image=866'
navigation_header:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Blog
    url: /blog/
navigation_footer:
  - title: Back to top
    url: '#top'
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-default-layout
  - jekyll-feed
  - jemoji
url: 'https://mydomain.com'
description: This is my new website
paginate: 5
paginate_path: 'blog/page:num'
