---
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: https://api.stackbit.com/project/5d979732d3d481001a0b76c2/webhook/forestry
sections:
- type: document
  path: _config.yml
  label: Config
  templates:
  - config
- type: document
  path: index.md
  label: Home
  templates:
  - home
- type: directory
  path: ''
  label: Page
  create: all
  match: "**/*.md"
  exclude: "{index.md,categories.md,_posts/**,README.md,LICENSE.md,index.md,categories.md}"
  templates:
  - page
- type: jekyll-posts
  label: Post
  create: all
  templates:
  - post
- type: document
  path: blog/index.html
  label: Blog
  templates:
  - blog
- type: document
  path: categories.md
  label: Categories Page
  templates:
  - categories
upload_dir: assets
public_path: "/assets"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
