---
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: 'https://api.stackbit.com/project/5d979732d3d481001a0b76c2/webhook/forestry'
sections:
  - type: document
    label: Config
    path: _config.yml
    templates:
      - config
  - type: document
    label: Home
    path: index.md
    templates:
      - home
  - type: directory
    path: ''
    match: '**/*.md'
    exclude: >-
      {index.md,categories.md,_posts/**,README.md,LICENSE.md,index.md,categories.md}
    label: Page
    create: all
    templates:
      - page
  - type: jekyll-posts
    label: Post
    create: all
    templates:
      - post
  - type: document
    label: Blog
    path: blog/index.html
    templates:
      - blog
  - type: document
    label: Categories Page
    path: categories.md
    templates:
      - categories
upload_dir: assets
public_path: /assets
front_matter_path: ''
use_front_matter_path: false
file_template: ':filename:'
